feat(NavBar): styles, sticky navbar...
ortizjavi/la-montaner pull request #125
Opened 2021-08-15 11:04 UTC by sebamuchut

Quedó a medio camino, pero por lo menos funciona la sticky navbar. Después le ponemos mejor diseño

2021-08-15 13:22 UTC, Lucas-FullStackX approved these changes
Nice

2021-08-15 15:00 UTC, NachoHotz requested changes
Fíjate Seba que en los dos archivos hay problemas de Merge. De resto esta genial!!

2021-08-15 15:56 UTC, GabiArrieta requested changes
buenisimo sebaaa, quedo solo lo del HEAD y los simbolitos para borrar en el navBar.css

2021-08-16 01:56 UTC, NachoHotz approved these changes
Joya Seba, ahora si!

2021-08-16 02:30 UTC, GabiArrieta approved these changes
genial!

2021-08-16 02:30 UTC, NachoHotz approved these changes

2021-08-16 02:30 UTC, merged